### ISSUE TITLE
Confusion about split row/col offset

### ISSUE THREAD

**Issue by thomasaarholt** [HaoboGu/rmk#164]
Hi again!
I'm a bit confused by the docs for the split keyboard, including the examples. 

For a split keyboard that has two identical 5x5 keys, for a total of 5 rows and 10 columns together, what is the correct col and row offset for the peripheral?

I would imagine it should be as per the following (most relevant bit is at the bottom of the code field, scroll):
```toml
[layout]
rows = 5
cols = 10
layers = 1
keymap = [
    [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
        ["A", "S", "D", "F", "G", "H", "J", "K", "L", "Quote"],
        ["Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash"],
        ["Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0"],
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    ],
]

[split.central]
rows = 5
cols = 5
row_offset = 0
col_offset = 0

[[split.peripheral]]
rows = 5
cols = 5
row_offset = 0 # <--- this bit is most interesting
col_offset = 5 # <--- this bit is most interesting
```

But in the [nrf ble split example](https://github.com/HaoboGu/rmk/blob/main/examples/use_config/nrf52840_ble_split/keyboard.toml), we have the following, where row offset is set to 2 for the peripheral.

```toml
[layout]
rows = 4
cols = 3

[split.central]
rows = 2
cols = 2
row_offset = 0
col_offset = 0

[[split.peripheral]]
rows = 2
cols = 1
row_offset = 2 # Is this incorrect? The row offset is zero, isn't it?
col_offset = 2
```

I have also looked at the [real life example](https://github.com/whitelynx/dactyl-lynx-rmk/blob/main/keyboard.toml) linked in the github repo readme, and that seems to do what I am doing, but also does strange things like having 14 rows and 6 cols, so I thought it best to ask.

I would have just tested it myself, but I am having a few issues with the keys not acting like I expected, and am debugging.
