### ISSUE TITLE
Multiple Tri Layer support

### ISSUE THREAD

**Issue by pcasotti** [HaoboGu/rmk#179]
Currently we only support one Tri Layer:
``` toml
[behavior]
tri_layer = { upper = 1, lower = 2, adjust = 3 }
```
The idea is to add support for multiple:
``` toml
[behavior]
tri_layers = [
    { upper = 1, lower = 2, adjust = 3 },
    { upper = 4, lower = 5, adjust = 6 }
]
```
