### ISSUE TITLE
Allow setting debounce time via `keyboard.toml`

### ISSUE THREAD

**Issue by gabevenberg** [HaoboGu/rmk#289]
Some switches need a bit more debounce time, should be able to be set by the user.

**Comment by HaoboGu** [comment]
now you can set the debounce time via:

```toml
[rmk]
# 20ms
debounce_time = 20
```
