### ISSUE TITLE
LTs are getting stuck

### ISSUE THREAD

**Issue by IniterWorker** [HaoboGu/rmk#362]
I have 4 LTs that I can use on a regular basis. Sometimes the LTs get stuck. When I think the planets are aligned and I get multiple LTs at the same time, the issue occurs. I didn’t run a debug session, but the problem happened twice in a row, and I had to reset the board each time.

* Platform: nrf 
* Ref: ab9a28bcb887deeae7b7de81a4125b5a75811541

Keyboard project: https://github.com/IniterWorker/rmk-lily58-keyboard

**Comment by HaoboGu** [comment]
Yeah, there's some tap-hold bugs. @hitsmaxft is working on it.

**Comment by hitsmaxft** [comment]
> the

enable hrm in behaviour config will fix the stuck , but multi LT still buggy , and i'm working on it

**Comment by HaoboGu** [comment]
Should be fixed by #371, @IniterWorker Could you try latest version with the following config?

```toml
[behavior]
# Enable HRM
tap_hold = { enable_hrm = true, permissive_hold = true, chordal_hold = true, prior_idle_time = "120ms", hold_timeout = "250ms" }
```
