### ISSUE TITLE
help to understand PIN naming for XIAO RP2040

### ISSUE THREAD

**Issue by eksandral** [HaoboGu/rmk#376]
Hi there. I am new in embed word, so my question probably will be naive.
I want to port qmk project for TOTEM keyboard to rmk. But for the moment no luck.
here is my `keyboard.toml` file 
```toml
[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "rp2040"

[layout]
rows = 4
cols = 5
layers = 1
keymap = [
    [
        ### Left
        ["Q", "W", "E", "R", "T"],
        ["A", "S", "D", "F", "G"],
        ["Z", "X", "C", "V", "B"],
        ["Q", "No", "Delete", "Tab", "Space"],
        ### Right
        ["Y", "U", "I", "O", "P"],
        ["H", "J", "K", "L", ";"],
        ["N", "M", ",", ".", "/"],
        ["Enter", "Escape", "No", "Backspace", "P"]
    ]
]

[storage]

[split]
connection = "serial"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "PIO1", tx_pin = "PIN_6", rx_pin = "PIN_7" }]

[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_0", "PIN_1", "PIN_2", "PIN_3"]
output_pins = ["PIN_4", "PIN_5", "PIN_10", "PIN_9", "PIN_8"]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 4
col_offset = 0
serial = [{ instance = "PIO0", tx_pin = "PIN_6", rx_pin = "PIN_7" }]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_0", "PIN_1", "PIN_2", "PIN_3"]
output_pins = ["PIN_4", "PIN_5", "PIN_10", "PIN_9", "PIN_8"]
```

I took the example of `sue_config` `rp2040_split_pio`
The project builds and can flash microcontrollers. But then they do nothing.
I am confused about the pin naming in QMK and RMK. Based on the official documentation of XIAO RP2040 by Seed Studio, it has some digital pins, micropython pins, and analog pins [XIAO-RP2040](https://wiki.seeedstudio.com/XIAO-RP2040/)
For example, in the QMK project, it is used like that
```
 "matrix_pins": {
        "rows": ["GP26", "GP27", "GP28", "GP29"],
        "cols": ["GP6", "GP7", "GP3", "GP4", "GP2"]
    },
    "diode_direction": "COL2ROW",
```
What will be the alternative for RMK?
